version: "3.1"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      BACKEND_DNS: "backend"
      BACKEND_PORT: "9000"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile