apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_USER
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: DB_USER
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: DB_NAME
#            - name: REDIS_PASSWORD
#              valueFrom:
#               secretKeyRef:
#                  name: redis-secret
#                  key: DB_PASSWORD

