name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build backend
      working-directory: ./backend
      run: go build -v .

    - name: Build frontend
      working-directory: ./frontend
      run: go build -v .

    - name: Test frontend
      working-directory: ./frontend
      run: go test -v .
